# Generated by Django 5.0.6 on 2024-07-10 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='bankrupt_check',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
